apiVersion: apps/v1
kind: Deployment
metadata:
  name: case-extraction-service
  labels:
    app: case-extraction-service
spec:
  selector:
    matchLabels:
      app: case-extraction-service
  template:
    metadata:
      labels:
        app: case-extraction-service
    spec:
      # serviceAccountName: data-service-account
      containers:
        - 
          name: case-extraction-service
          image: 691195436300.dkr.ecr.us-east-1.amazonaws.com/case_extraction:latest
          resources:
            limits: 
              cpu: 1500m
              memory: 3000Mi
            requests:
              cpu: 1500m
              memory: 3000Mi
          env:
            - 
              name: ENV
              value: "dev" 
            - 
              name: GIT_BRANCH
              value: "malden-center-dev-debug"
      nodeSelector:
        nodeType: worker
