apiVersion: apps/v1
kind: Deployment
metadata:
  name: redaction-service
  labels:
    app: redaction-service
spec:
  selector:
    matchLabels:
      app: redaction-service
  template:
    metadata:
      labels:
        app: redaction-service
    spec:
      # serviceAccountName: data-service-account
      containers:
        -
          name: redaction-service
          image: 691195436300.dkr.ecr.us-east-1.amazonaws.com/redaction:feature-iscd-4184
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 3
              memory: 6Gi
            requests:
              cpu: 3
              memory: 6Gi
          env:
            -
              name: ENV
              value: "dev"
