apiVersion: apps/v1
kind: Deployment
metadata:
  name: procedure-detection-service
  labels:
    app: procedure-detection-service
spec:
  selector:
    matchLabels:
      app: procedure-detection-service
  template:
    metadata:
      labels:
        app: procedure-detection-service
    spec:
      containers:
        -
          name: procedure-detection-service
          image: 691195436300.dkr.ecr.us-east-1.amazonaws.com/procedure_detection:fix-ISCD-3054
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 1
              memory: 2Gi
            requests:
              cpu: 1
              memory: 2Gi
          env:
            -
              name: ENV
              value: "qa"

