apiVersion: apps/v1
kind: Deployment
metadata:
  name: case-extraction-service
  labels:
    app: case-extraction-service
spec:
  selector:
    matchLabels:
      app: case-extraction-service
  template:
    metadata:
      labels:
        app: case-extraction-service
    spec:
      # serviceAccountName: data-service-account
      containers:
        -
          name: case-extraction-service
          image: 691195436300.dkr.ecr.us-east-1.amazonaws.com/case_extraction:20.21-green-st-hotfix
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 3
              memory: 6Gi
            requests:
              cpu: 3
              memory: 6Gi
          env:
            -
              name: ENV
              value: "qa"
